### ISSUE TITLE
Theme and colors of the website

### ISSUE THREAD

**Issue by sekharjha** [techhub-community/techhub-website#14]
Lets decide a common theme(fonts and styling) and colors for the website.
i would like everyone to go through this link
[(http://colormind.io)] 
@adikeshri  @iavinas  @dntandan

**Comment by adikeshri** [comment]
Colour palette is already defined. You can find it in one of the closed issues

**Comment by dntandan** [comment]
@sekharjha for the color scheme you can refer to the #6 issue and kindly give some suggestions on the font.

**Comment by sekharjha** [comment]
ok i am closing this issue as the color is resolved.
