### ISSUE TITLE
Design logo and asthetics

### ISSUE THREAD

**Issue by adikeshri** [techhub-community/techhub-website#4]

**Comment by adikeshri** [comment]
Acceptance criteria:
- Decide colour palette
- Design logo based on that colour palette

**Comment by dntandan** [comment]
![avatar-square](https://user-images.githubusercontent.com/32794634/114772500-827a4c00-9d8b-11eb-8ebc-60d5786374ca.png)
![avatar-square-dark](https://user-images.githubusercontent.com/32794634/114772519-860dd300-9d8b-11eb-8574-9846ded1da14.png)
![avatar-transparent](https://user-images.githubusercontent.com/32794634/114772527-873f0000-9d8b-11eb-98c0-8ed27f15f020.png)
![logo-dark-full-transparent](https://user-images.githubusercontent.com/32794634/114772530-8908c380-9d8b-11eb-8724-abf5012facf6.png)
![logo-dark-square](https://user-images.githubusercontent.com/32794634/114772532-89a15a00-9d8b-11eb-97c1-e9a30ea19ea6.png)
![logo-full-transparent](https://user-images.githubusercontent.com/32794634/114772535-8a39f080-9d8b-11eb-9944-0936415a1b95.png)
![logo-square](https://user-images.githubusercontent.com/32794634/114772538-8ad28700-9d8b-11eb-8e33-17c483f9c96b.png)

**Comment by dntandan** [comment]
@adikeshri @iavinas

**Comment by dntandan** [comment]
I am closing this issue. Feel free to reopen it if needed. @adikeshri @iavinas
