### ISSUE TITLE
Add getting started with node and yarn in docs with links

### ISSUE THREAD

**Issue by dntandan** [techhub-community/techhub-website#51]

**Comment by codewithkushagra** [comment]
Can I added the doc link in read me for node and yarn

**Comment by dntandan** [comment]
@codewithkushagra go ahead with this. Do pull dev changes first and make PR to dev branch only.

**Comment by codewithkushagra** [comment]
@dntandan I didn't had the repo forked so, forked it just now and made the changes in code and did a PR. No pull was required na cause I just forked and dev code was up to date

**Comment by dntandan** [comment]
great.

**Comment by dntandan** [comment]
Closing this isssue as PR #59 has been merged
