### ISSUE TITLE
Finalize Color Palette 

### ISSUE THREAD

**Issue by dntandan** [techhub-community/techhub-website#6]

**Comment by dntandan** [comment]
![](https://user-images.githubusercontent.com/32794634/114772908-ffa5c100-9d8b-11eb-9b44-413abaea3d51.png)

![](https://user-images.githubusercontent.com/32794634/114772940-0d5b4680-9d8c-11eb-8d34-02b7ed2fee9d.png)

**Comment by dntandan** [comment]
@adikeshri

**Comment by adikeshri** [comment]
Second one looks good. More diversified. But maybe add one more lighter shade of pink.

What do you think? @dntandan @iavinas @AvikantSrivastava @sekharjha

**Comment by dntandan** [comment]
![](https://user-images.githubusercontent.com/32794634/114874933-6f628d00-9e1a-11eb-8c11-51d51400366e.png)

**Comment by dntandan** [comment]
These will be our new TailwindCSS color shades for the above 5 colors.

![](https://user-images.githubusercontent.com/32794634/114875564-0af3fd80-9e1b-11eb-8c6d-d32bf55ec3a7.png)

**Comment by dntandan** [comment]
Or instead of two black shades, we can go for one blue shade also like this  
  
 

![](https://user-images.githubusercontent.com/32794634/114876678-2dd2e180-9e1c-11eb-8664-da83b56968b1.png)

![](https://user-images.githubusercontent.com/32794634/114876600-1ac01180-9e1c-11eb-8c28-caa23299ce84.png)

**Comment by adikeshri** [comment]
Looks good💯

**Comment by dntandan** [comment]
I am closing and locking this issue now considering we are going with the last template [https://github.com/techhub-community/techhub-website/issues/6#issuecomment-820420814](https://github.com/techhub-community/techhub-website/issues/6#issuecomment-820420814)  
  
Feel free to ask in discussions if anyone wants additional information.
