### ISSUE TITLE
TechHub in numbers

### ISSUE THREAD

**Issue by adikeshri** [techhub-community/techhub-website#9]
Show techhub in numbers in webpage.

For example:
Number of members(Fetch from discord server)
Projects running: Fetch from Github maybe? Can also add github stars here.

Let's create a  mockup for this first.

**Comment by dntandan** [comment]
a small version is already on the latest iteration of webpage https://tech-hub.org

**Comment by adikeshri** [comment]
Yes, looks good.

I was refering to something like this at the botton of the page

https://images.app.goo.gl/T9L1VcFjKkAKV8cY9

**Comment by dntandan** [comment]
Can be implemented...Will add it to the roadmap of the website dev phase.

**Comment by adikeshri** [comment]
Picking this up, needed for initial release
